name: CI

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    - name: "Run test suite"
      uses: msfjarvis/setup-android@1.0
      with:
        entrypoint: ./gradlew
        args: build
